### ISSUE TITLE
timeout for the tree_parse

### ISSUE THREAD

**Issue by xgal** [tree-sitter/py-tree-sitter#144]
Hi!
Thanks for your contribution
I saw there is an option to set a timeout in ms for the TS in Rust
Is it possible to add it to the binding ?
I saw examples where the code wasn't parsable, leading to infinite recursion.

Thanks

**Comment by amaanq** [comment]
Infinite parses shouldn't happen, so that's a bug with whichever language parser you're using, I would be curious to know which one. You should also file a bug with that language's repo if `tree-sitter parse <file>` hangs as well, indicating it's not a bug here.

However, I agree adding the timeout stuff here would be nice (but that'll be reworked somewhat soon maybe)
