### ISSUE TITLE
How to sync node after code edit?

### ISSUE THREAD

**Issue by zch-cc** [tree-sitter/py-tree-sitter#183]
Hi, first of all thanks for making tree sitter.
I have a question for how to sync node after code edit? 
After the code edit, the orginal node.text return None. Is there an api to let the node keep sync and return the full text? The use case is I want to cache all function node in the current file(update every three seconds) and want to use node.text in the subsequence processing. Is there a good way to implement this kind of feature?
I saw the issue https://github.com/tree-sitter/py-tree-sitter/issues/85 is closed because of pr https://github.com/tree-sitter/py-tree-sitter/pull/150 but I am still confuse how to use it. Do I do node.edit for each node that are affected by the update?

**Comment by amaanq** [comment]
`Node.edit` syncs them

**Comment by jmehnle** [comment]
I ran into this limitation, and what I found is that there's no way to fully update nodes that were extracted from a tree prior to an edit of that tree. The `text` returns `None` because the source text of the original tree is deallocated (presumably both to serve memory and to avoid confusion, because the _original_ tree no longer represents the _newly parsed_ tree's source text). In fact, some nodes may no longer be related to the newly parsed tree at all.

If you have a number of non-overlapping edits, the proper way to approach this is to first determine all the edits with their locations, and then apply them to the source text in reverse order (bottommost edits first). If you want to benefit from Tree Sitter's fast incremental parse, then also call `Tree.edit()` and `Parser.parse()` after each edit, however depending on the number of edits this may end up costing more resources than just applying the edits to the source text and doing a full parse from scratch at the very end.
