### ISSUE TITLE
Python 3.12 support for version 0.21.0

### ISSUE THREAD

**Issue by thomashart17** [tree-sitter/py-tree-sitter#209]
I want to upgrade to use version 0.21.0 of Tree Sitter in a project I've been working on so I don't have to clone and build each language implementation manually. I'm using Python 3.12 for the project and it looks like this is not supported in version 0.21.0. Previous versions of the library were supported for all Python versions >= 3.3, so I'm not sure why this was changed for the latest version? I would appreciate if support could be added for this.

**Comment by ObserverOfTime** [comment]
Python 3.12 removed `distutils` which is required by the deprecated `Language.build_library` function. The previous version depended on `setuptools` to provide the `distutils` API on 3.12, but I removed the dependency because the function will also be gone in the next version. You can still install the project like this if you don't need that function:

```bash
pip install tree-sitter==0.21 --ignore-requires-python
```

**Comment by ObserverOfTime** [comment]
v0.21.1 supports Python 3.12 again.
