### ISSUE TITLE
libc++ conflict with libstdc++ with Linux and Anaconda

### ISSUE THREAD

**Issue by colinclement** [tree-sitter/py-tree-sitter#27]
When I try to run `Language.build_library('languages.so', ['tree-sitter-python'])` on a machine using an Anaconda python distribution (which uses libstdc++) and my Ubuntu 16 system has both libc++ and libstdc++ installed, `build_library` [gives higher precedence](https://github.com/tree-sitter/py-tree-sitter/blob/dd07df5434a9795e6079707cbbb4a048c4a3885a/tree_sitter/__init__.py#L47) to the existence of libc++, when libstdc++ is necessary for use with my Anaconda python. The result of this is that I get the error

`/usr/bin/ld: cannot find -lc++`.

I recognize this is strange since I have both installed, but perhaps the distutils compiler only pays attention to Anaconda library paths?

I fixed it on my system by giving higher precedence to libstdc++ (and can submit a PR), but would this break py-tree-sitter for others? Is there another way to fix this logic so it works? Since libc++ is 'newer' than libstdc++, perhaps the precedence of the older one makes sense?

**Comment by boba-and-beer** [comment]
I don't have Anaconda installed and I encountered the same issue so I don't think it's an anaconda-specific problem. Not a maintainer, but I think creating a PR would help resolve the problem for a fair few others as well (including me!)

**Comment by sogaiu** [comment]
FWIW, I think there might also be some relevant info in this issue: https://github.com/tree-sitter/py-tree-sitter/issues/41

**Comment by maxbrunsfeld** [comment]
Has anyone come up with a general solution to this that could be incorporated into the library? It would be great if we could somehow detect what version of the C++ standard library the current Python interpreter is linked against (if any).

**Comment by narpfel** [comment]
I believe the problem is caused by the fact that `distutils` uses `cc` as the driver to link the final shared object, so the C++ standard library (`libstdc++` or `libc++`, depending on the platform) is not linked automatically. If `c++` were used, the compiler should automatically select the correct (default) STL for the current platform.

I’m not sure if this is the proper API to change the compiler executable in `distutils`, but this (somewhat hacky?) patch fixes the problem for me:
```patch
diff --git a/tree_sitter/__init__.py b/tree_sitter/__init__.py
index cc94ac9..b2e23d4 100644
--- a/tree_sitter/__init__.py
+++ b/tree_sitter/__init__.py
@@ -3,6 +3,7 @@
 from ctypes import cdll, c_void_p
 from ctypes.util import find_library
 from distutils.ccompiler import new_compiler
+from distutils.unixccompiler import UnixCCompiler
 from os import path
 from platform import system
 from tempfile import TemporaryDirectory
@@ -43,11 +44,8 @@ class Language:
         ]
 
         compiler = new_compiler()
-        if cpp:
-            if find_library("c++"):
-                compiler.add_library("c++")
-            elif find_library("stdc++"):
-                compiler.add_library("stdc++")
+        if isinstance(compiler, UnixCCompiler):
+            compiler.compiler_cxx[0] = "c++"
 
         if max(source_mtimes) <= output_mtime:
             return False
@@ -69,7 +67,11 @@ class Language:
                         extra_preargs=flags,
                     )[0]
                 )
-            compiler.link_shared_object(object_paths, output_path)
+            compiler.link_shared_object(
+                object_paths,
+                output_path,
+                target_lang="c++" if cpp else "c",
+            )
         return True
 
     def __init__(self, library_path, name):

```
This should let the C++ compiler link the same STL as is expected by `scanner.cc`. I don’t have access to a Mac so I only tested this on Linux.

**Comment by maxbrunsfeld** [comment]
If anyone has the time and ability to thoroughly test this (or any other) approach, I'd definitely be open to merging it. I think it's fine as long as it can be shown to work on macOS, some common linux distro, and windows.

**Comment by narpfel** [comment]
@maxbrunsfeld What would you consider a thorough test for this? Would passing the test suite be enough? As one of the tests uses `tree-sitter-python` (which has a `scanner.cc` file), compiling and loading the resulting tree sitter library should be sufficient to find out if the correct STL was linked.

Because the `py-tree-sitter` CI currently does not test on Mac, I set up a GitHub action to test this on Ubuntu (with and without `libc++` installed), Windows and Mac [here](https://github.com/narpfel/py-tree-sitter/blob/18c7111b04ccff8f5bf5aae5553ecc38489bb9c0/.github/workflows/ci.yml). CI results [here](https://github.com/narpfel/py-tree-sitter/actions/runs/817660393). (Note that the build failure for PyPy on Mac is not related to the patch, but also present on current master.)

If this is OK for you, I will make a PR. Should I include the GitHub action?

**Comment by maxbrunsfeld** [comment]
> What would you consider a thorough test for this? Would passing the test suite be enough?

👍  Yes.

> Note that the build failure for PyPy on Mac is not related to the patch, but also present on current master

That's strange; I personally develop on a mac, and the tests run fine for me. The error message is interesting:

```
clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
tests/fixtures/tree-sitter-python/src/scanner.cc:2:10: fatal error: 'vector' file not found
#include <vector>
         ^~~~~~~~
```

It looks like, for *some* reason, the flag `-stdlib=libstdc++` is being passed to clang, indicating that it should use the non-default C++ standard library.

**Comment by narpfel** [comment]
I reran the tests without `--quiet`. [This](https://github.com/narpfel/py-tree-sitter/pull/1/checks?check_run_id=2521022314#step:9:45) is the compiler invocation on PyPy/Mac that errors:
```
cc -arch x86_64 -fPIC -Itests/fixtures/tree-sitter-python/src -c tests/fixtures/tree-sitter-python/src/scanner.cc -o /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpg8_knoprtree_sitter_language/tests/fixtures/tree-sitter-python/src/scanner.o
```
and [on Python3.8/Mac](https://github.com/narpfel/py-tree-sitter/pull/1/checks?check_run_id=2521022250#step:9:36):
```
cc -fPIC -Itests/fixtures/tree-sitter-python/src -c tests/fixtures/tree-sitter-python/src/scanner.cc -o /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpqvfc5o5vtree_sitter_language/tests/fixtures/tree-sitter-python/src/scanner.o
```
So the only difference is `-arch`? I don’t see why this should influence `clang`’s include path, though I don’t know Apple Clang at all.

**Comment by maxbrunsfeld** [comment]
Oh, I think it's because we should be using `c++` instead of `cc` as the executable?

**Comment by narpfel** [comment]
> Oh, I think it's because we should be using `c++` instead of `cc` as the executable?

It shouldn’t matter. `cc` as the compiler driver usually selects the right compiler based on the extension.

> I also think it's fine to just not include PyPy on mac in our CI matrix.

[Done.](https://github.com/tree-sitter/py-tree-sitter/commit/501e23f8ed0bd63d70f8ffa852174cb5fca940b5#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR30-R31)
