### ISSUE TITLE
Request: can we get a release to fix the build issues on ubuntu for grammars with external scanners?

### ISSUE THREAD

**Issue by ahelwer** [tree-sitter/py-tree-sitter#69]
Specifically one that includes this commit: https://github.com/tree-sitter/py-tree-sitter/commit/b4db17e4d43f27a040b4bf087695cc200512e4ea

**Comment by lunixbochs** [comment]
> Still would be nice to get a release for user experience reasons, since outside of CI we can't really ask all people building & consuming python tools to uninstall libc++.

Closing as we've had a release since this issue, and our CI is currently passing on Ubuntu on GitHub Actions. Let me know if a specific parser is giving you issues on Linux, and I can run CI specifically for that.

--

Separately, @m-kru, your fbdl parser builds fine in GitHub Actions against latest HEAD: https://github.com/tree-sitter/py-tree-sitter/runs/5112682859?check_suite_focus=true
(It only fails on the windows runners because you `#include <err.h>`, which is not supported in MSVC)
