### ISSUE TITLE
Missing parser.c error for typescript

### ISSUE THREAD

**Issue by prabhu** [tree-sitter/py-tree-sitter#75]
While trying to invoke `build_library` with typescript is resulting in missing src/parser.c error. Is there any documentation on which languages are supported with the python binding?

**Comment by dkt2** [comment]
I had the same problem 👋 

The TypeScript package is weird because it contains two grammars: `typescript` and `tsx`. Pointing to just the root of `tree-sitter-typescript` (or `tree-sitter-typescript-master` if you just cloned it from GitHub) will return a "can't find file: `src/parser.c`" because that file is located in the nested folder `typescript` or `tsx`. 

To fix the problem: give the path to `build_library` as `.../tree-sitter-typescript-master/tsx` (if you want to work with TypeScript JSX) or `.../tree-sitter-typescript-master/typescript` (if you just want TypeScript).
