### ISSUE TITLE
ModuleNotFoundError: No module named 'tree_sitter.binding' when building *.so

### ISSUE THREAD

**Issue by Symbolk** [tree-sitter/py-tree-sitter#84]
Hi, I have replicated the problem both on windows and macos, here is what I did:

1. clone the repo and update the submodule
2. create venv and pip install tree_sitter
3. clone tree-sitter-java under vendor/
4. run the following build script modified from README:

```python
from tree_sitter import Language, Parser

Language.build_library(
  # Store the library in the `build` directory
  'build/javalang.so',

  # Include one or more languages
  [
    'vendor/tree-sitter-java'
  ]
)

JAVA_LANGUAGE = Language('build/javalang.so', 'java')
```
However, it gives me the following error:

```
Traceback (most recent call last):
  File "/Users/symbolk/coding/analysis/treesitter/py-tree-sitter/builder.py", line 1, in <module>
    from tree_sitter import Language, Parser
  File "/Users/symbolk/coding/analysis/treesitter/py-tree-sitter/tree_sitter/__init__.py", line 9, in <module>
    from tree_sitter.binding import _language_field_id_for_name, _language_query
ModuleNotFoundError: No module named 'tree_sitter.binding'

```

**Comment by Symbolk** [comment]
BTW, binding is resolvable in PyCharm, that's what makes me confused:
![image](https://user-images.githubusercontent.com/14107297/150126967-19a28ce5-15f7-46bd-bda9-a1fe6b35b7aa.png)

**Comment by narpfel** [comment]
If you’re inside the source directory of `py-tree-sitter`, `import tree_sitter` will try to import the git clone and not the version installed from PyPI (because `.` is the first entry in [`sys.path`](https://docs.python.org/3/library/sys.html#sys.path)). But this does not work because `tree_sitter.binding` is a native module that has to be compiled first.

If you want to work with the git clone, you have to install *that* using `pip install -e .` (which compiles `tree_sitter.binding`). If you just want to *use* `py-tree-sitter`, there should not be a need to clone the repo, just installing from PyPI should be sufficient.

**Comment by Symbolk** [comment]
> If you’re inside the source directory of `py-tree-sitter`, `import tree_sitter` will try to import the git clone and not the version installed from PyPI (because `.` is the first entry in [`sys.path`](https://docs.python.org/3/library/sys.html#sys.path)). But this does not work because `tree_sitter.binding` is a native module that has to be compiled first.
> 
> If you want to work with the git clone, you have to install _that_ using `pip install -e .` (which compiles `tree_sitter.binding`). If you just want to _use_ `py-tree-sitter`, there should not be a need to clone the repo, just installing from PyPI should be sufficient.

Thanks! Personally I also figured this out when sleeping, but your response surely lets me know more!
