### ISSUE TITLE
ASan in CI

### ISSUE THREAD

**Issue by lunixbochs** [tree-sitter/py-tree-sitter#88]
@narpfel can you help me set up ASan and leak tests on CI? We can probably just do it for the Ubuntu runners, and even run a single Ubuntu job on a specific version of Python if necessary.

**Comment by narpfel** [comment]
Locally I test with a debug build of Python compiled with
```console
$ ./configure --with-assertions --with-address-sanitizer --with-undefined-behavior-sanitizer --with-pydebug --disable-shared --prefix=$prefix
```

Just compiling the TS binding with ASan doesn’t really work because all `PyObject`s allocated in the extension are tracked by ASan, but `free`ing them outside the extension isn’t.

I’m not aware of any prebuilt binaries that could be used here, and there are no open issues about debug builds on [actions/setup-python](https://github.com/actions/setup-python) and [deadsnakes/issues](https://github.com/deadsnakes/issues), so compiling Python in CI seems easiest?

**Comment by lunixbochs** [comment]
Sweet, thanks, I got it working in the `ci-asan` branch.

Here's a run with ASAN, finding no leaks:
- https://github.com/tree-sitter/py-tree-sitter/runs/5239569252

Here's a run with ASAN and all the decrefs removed, which finds a ton of leaks and fails as expected:
- https://github.com/tree-sitter/py-tree-sitter/runs/5239483877
